set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CWAIT]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports START]
set_property IOSTANDARD LVCMOS33 [get_ports Y]

set_property PACKAGE_PIN P4 [get_ports CLK]
set_property PACKAGE_PIN P3 [get_ports CWAIT]
set_property PACKAGE_PIN R3 [get_ports RST]
set_property PACKAGE_PIN T1 [get_ports START]
set_property PACKAGE_PIN P2 [get_ports G]
set_property PACKAGE_PIN U1 [get_ports R]
set_property PACKAGE_PIN R2 [get_ports Y]
