webtalk_init -webtalk_dir D:/Projects/Vivado_Projects/Lab3/Lab3.sim/sim_1/synth/func/xsim/xsim.dir/task2_RS_Latch_struct_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov  1 14:37:27 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c45547c0-e9a2-4f9d-8093-7a73ca619e69" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "98747a9a4cf745d99138974d0bac539a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1020 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "10000" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2739308578 -regid "" -xml D:/Projects/Vivado_Projects/Lab3/Lab3.sim/sim_1/synth/func/xsim/xsim.dir/task2_RS_Latch_struct_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/Projects/Vivado_Projects/Lab3/Lab3.sim/sim_1/synth/func/xsim/xsim.dir/task2_RS_Latch_struct_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/Projects/Vivado_Projects/Lab3/Lab3.sim/sim_1/synth/func/xsim/xsim.dir/task2_RS_Latch_struct_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
